[package]
name = "helium-ticker"
version = "0.1.0"
authors = ["Shane Snover <ssnover95@gmail.com>"]
edition = "2018"

[[bin]]
name = "hnt"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
serde = "1.0"
serde_json = "1.0"
